import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tour Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fluur-favicon.png" />
      </Head>
    </div>
  );
};

export default Home;
