import type { NextPage } from "next";
import Head from "next/head";
import ToursSection from "../src/sections/tours";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Tour Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fluur-favicon.png" />
      </Head>
      <ToursSection />
    </>
  );
};

export default Home;
